### ISSUE TITLE
Plugin won't load?

### ISSUE THREAD

**Issue by ewanjwilson** [Jannyboy11/CustomRecipes#17]
[16:56:25] [Server thread/ERROR]: Could not load 'plugins/CustomRecipes-2.2.1 (2).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_12_R1/inventory/CraftItemStack
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_12_R1/inventory/CraftItemStack
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_151]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_151]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[server.jar:git-Spigot-21fe707-e1ebe52]
... 6 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_151]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_151]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[server.jar:git-Spigot-21fe707-e1ebe52]
... 6 more

**Comment by TomLewis** [comment]
It also does not load for me

[14:36:01] [Server thread/INFO]: [CustomRecipes] Enabling CustomRecipes v2.2.1-SNAPSHOT
[14:36:01] [Server thread/ERROR]: Error occurred while enabling CustomRecipes v2.2.1-SNAPSHOT (Is it up to date?)
java.lang.RuntimeException: java.util.zip.ZipException: Not in GZIP format
	at com.gmail.jannyboy11.customrecipes.CustomRecipesPlugin.lambda$onLoad$2(CustomRecipesPlugin.java:194) ~[?:?]
	at java.util.function.Function.lambda$andThen$1(Function.java:88) ~[?:1.8.0_151]
	at com.gmail.jannyboy11.customrecipes.CustomRecipesPlugin.lambda$onEnable$36(CustomRecipesPlugin.java:443) ~[?:?]
	at java.util.TreeMap.forEach(TreeMap.java:1005) ~[?:1.8.0_151]
	at com.gmail.jannyboy11.customrecipes.CustomRecipesPlugin.onEnable(CustomRecipesPlugin.java:439) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1268]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1268]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1268]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [patched_1.12.2.jar:git-Paper-1268]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [patched_1.12.2.jar:git-Paper-1268]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1268]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1268]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1268]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1268]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1268]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165) ~[?:1.8.0_151]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:1.8.0_151]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:18) ~[patched_1.12.2.jar:git-Paper-1268]
	at com.gmail.jannyboy11.customrecipes.util.NBTUtil.readNBTTagCompound(NBTUtil.java:66) ~[?:?]
	at com.gmail.jannyboy11.customrecipes.CustomRecipesPlugin.lambda$onLoad$2(CustomRecipesPlugin.java:192) ~[?:?]
	... 15 more
[14:36:01] [Server thread/INFO]: [CustomRecipes] Disabling CustomRecipes v2.2.1-SNAPSHOT

**Comment by EpicRealms** [comment]
It doens't load for me either
