### ISSUE TITLE
Custom Mob Head Items

### ISSUE THREAD

**Issue by Rixic** [Jannyboy11/CustomRecipes#21]
(Permission) Crafting recipes with custom player heads seem to cause issues, they are not craftable by players with the permission node but are craftable by ops, attempting to remove a recipe gives a console error.

Version: Paper-1414 (1.12.2)

`02/07/2018 21:56:26 [INFO] Rixic issued server command: /removerecipe permission
02/07/2018 21:56:26 [WARN] java.lang.IllegalArgumentException: value already present: com.gmail.jannyboy11.customrecipes.impl.crafting.custom.recipe.PermissionRecipe@72233979
02/07/2018 21:56:26 [WARN] 	at com.google.common.collect.HashBiMap.putInverse(HashBiMap.java:323)
02/07/2018 21:56:26 [WARN] 	at com.google.common.collect.HashBiMap.access$800(HashBiMap.java:58)
02/07/2018 21:56:26 [WARN] 	at com.google.common.collect.HashBiMap$Inverse.put(HashBiMap.java:579)
02/07/2018 21:56:26 [WARN] 	at com.gmail.jannyboy11.customrecipes.impl.crafting.CRCraftingManager.toNMSRecipe(CRCraftingManager.java:213)
02/07/2018 21:56:26 [WARN] 	at com.gmail.jannyboy11.customrecipes.impl.crafting.CRCraftingManager.removeRecipe(CRCraftingManager.java:328)
02/07/2018 21:56:26 [WARN] 	at com.gmail.jannyboy11.customrecipes.impl.crafting.custom.addremove.PermissionRemover.accept(PermissionRemover.java:75)
02/07/2018 21:56:26 [WARN] 	at com.gmail.jannyboy11.customrecipes.impl.crafting.custom.addremove.PermissionRemover.accept(PermissionRemover.java:17)
02/07/2018 21:56:26 [WARN] 	at com.gmail.jannyboy11.customrecipes.commands.RemoveRecipeCommandExecutor.onCommand(RemoveRecipeCommandExecutor.java:41)
02/07/2018 21:56:26 [WARN] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
02/07/2018 21:56:26 [WARN] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
02/07/2018 21:56:26 [WARN] 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
02/07/2018 21:56:26 [WARN] 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472)
02/07/2018 21:56:26 [WARN] 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277)
02/07/2018 21:56:26 [WARN] 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
02/07/2018 21:56:26 [WARN] 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
02/07/2018 21:56:26 [WARN] 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
02/07/2018 21:56:26 [WARN] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
02/07/2018 21:56:26 [WARN] 	at java.util.concurrent.FutureTask.run(Unknown Source)
02/07/2018 21:56:26 [WARN] 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
02/07/2018 21:56:26 [WARN] 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
02/07/2018 21:56:26 [WARN] 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
02/07/2018 21:56:26 [WARN] 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
02/07/2018 21:56:26 [WARN] 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
02/07/2018 21:56:26 [WARN] 	at java.lang.Thread.run(Unknown Source)`

**Comment by Rixic** [comment]
nvm, figured out why players could not craft the item however that console error is still an issue.
